export const fakeData = {
  users: [
    {
      _id: "6368a5c7d2969c60b9a58f74",
      authId: "6368a5c7d2969c60b9a58f73",
      username: "Izuku",
      profilePicture:
        "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667802571/6368a5c7d2969c60b9a58f74",
      postsCount: 4,
      followersCount: 0,
      followingCount: 0,
      passwordResetToken: "",
      blocked: [],
      blockedBy: [],
      notifications: {
        messages: true,
        reactions: true,
        comments: true,
        follows: true,
      },
      social: {
        facebook: "",
        instagram: "",
        twitter: "",
        youtube: "",
      },
      work: "",
      school: "",
      location: "",
      quote: "",
      bgImageVersion: "",
      bgImageId: "",
      __v: 0,
    },
    {
      _id: "6368a5c7d2969c60b9a58f75",
      authId: "6368a5c7d2969c60b9a58f74",
      username: "Asta",
      profilePicture: "",
      postsCount: 4,
      followersCount: 0,
      followingCount: 0,
      passwordResetToken: "",
      blocked: [],
      blockedBy: [],
      notifications: {
        messages: true,
        reactions: true,
        comments: true,
        follows: true,
      },
      social: {
        facebook: "",
        instagram: "",
        twitter: "",
        youtube: "",
      },
      work: "",
      school: "",
      location: "",
      quote: "",
      bgImageVersion: "",
      bgImageId: "",
      __v: 0,
    },
  ],
};
